Repository micronaut-projects/micronaut-platform, pull requests merged in 2023-07, with the labels that each got.

#617 [platform] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#665 [platform] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#675 Add plugins to parent POM
  gradle/libs.versions.toml
  parent/src/pom-template.xml
Labels: type: improvement

#696 RabbitMQ m8
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#702 ElasticSearch M7
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#703 Email M6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#704 Logging M6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#734 Update to GA versions
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#739 test resources to 2.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#741 Maven to 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#747 Update libs.versions.toml
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#751 Jackson XML 4.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#801 [platform] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#802 Data 4.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#807 [platform] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#813 Micronaut core 4.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#815 CRaC 2.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
