Repository micronaut-projects/micronaut-platform, pull requests merged in 2023-04, with the labels that each got.

#225 Upgrade to Micronaut Build 6.4.0
  buildSrc/src/main/java/io/micronaut/build/internal/RewritePom.java
  buildSrc/src/main/kotlin/io.micronaut.build.internal.maven-pom.gradle.kts
  settings.gradle
Labels: relates-to: build, type: dependency-upgrade

#227 [platform] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#226 Upgrade core and Maven to milestone
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#235 rabbitmq M2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#236 servlet M2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
