Repository micronaut-projects/micronaut-platform, pull requests merged in 2024-02, with the labels that each got.

#1266 Add missing goal for the native tests profile
  parent/src/pom-template.xml
Labels: type: bug

#1301 [platform] Update common files for branch 4.4.x
  .github/workflows/graalvm-dev.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#1305 build: AWS 4.4.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#1308 dep: micronaut-security 4.6.6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
