Repository micronaut-projects/micronaut-platform, pull requests merged in 2024-04, with the labels that each got.

#1406 Ignore existing GraalVM resources-config.json files when autodetecting resources
  parent/src/pom-template.xml
Labels: type: bug

#1421 core 4.4.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#1429 Update maven plugin to 4.5.3 for Micronaut 4.4.1
  gradle/libs.versions.toml
Labels: type: bug

#1428 Remove regressions that no longer cause issues
  platform/build.gradle.kts
Labels: relates-to: build

#1427 breaks: del RxJava2 from MN 5.0.0 BOM
  gradle/libs.versions.toml
  platform/build.gradle.kts
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/toc.yml
Labels: relates-to: build, type: breaking

#1439 Remove microstream from Micronaut 5.0.0 BOM
  gradle/libs.versions.toml
  platform/build.gradle.kts
  src/main/docs/guide/breaks.adoc
Labels: type: breaking

#1453 views 5.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
